language: scala

jdk: openjdk8

scala:
  - 2.11.12
  - 2.12.10

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - sudo apt-get -y install perl
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

services:
  - postgresql

before_script:
  - psql -c "ALTER USER postgres PASSWORD 'postgres';"
  - psql -c "create database almaren;"
  - psql -U postgres -d almaren -f src/test/resources/tables.ddl

script:
  - sbt +test



